micronaut:
  application:
    name: student
  security:
    enabled: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/mn_student
    username: postgres
    password: ***
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - 'ru.vtarasov.mn.student'
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog/db.changelog-master.yaml'